server:
    port: 8080

spring:
    datasource:
        name: db1
        url: jdbc:mysql://127.0.0.1:3306/db1?serverTimezone=UTC
        username: root
        password: 111111
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapper-locations: classpath:mappers/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: com.example.demo.entity